# Generated by Django 5.1.2 on 2024-11-15 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
        ('Common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RBoxImage',
            fields=[
                ('id', models.CharField(editable=False, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Common.image')),
            ],
            options={
                'verbose_name': 'RBox Image',
                'verbose_name_plural': 'RBox Images',
                'db_table': 'rbox_image',
            },
        ),
        migrations.CreateModel(
            name='RBox',
            fields=[
                ('id', models.CharField(editable=False, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('images', models.ManyToManyField(to='Admin.rboximage')),
            ],
            options={
                'verbose_name': 'RBox',
                'verbose_name_plural': 'RBoxes',
                'db_table': 'rbox',
            },
        ),
    ]
