# Generated by Django 5.1.2 on 2024-10-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False, unique=True)),
                ('url', models.CharField(max_length=255)),
                ('alt', models.CharField(blank=True, max_length=255, null=True)),
                ('caption', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(default='cloudinary', max_length=255)),
            ],
            options={
                'verbose_name': 'image',
                'verbose_name_plural': 'images',
                'db_table': 'images',
            },
        ),
        migrations.CreateModel(
            name='ItemMedia',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False, unique=True)),
                ('url', models.CharField(max_length=255)),
                ('alt', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(default='cloudinary', max_length=255)),
            ],
            options={
                'verbose_name': 'item media',
                'verbose_name_plural': 'item media',
                'db_table': 'item_media',
            },
        ),
    ]
