# Generated by Django 5.1.2 on 2024-10-24 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Common', '0001_initial'),
        ('Inventory', '0003_alter_item_can_return_alter_item_delivery_time_and_more'),
    ]

    operations = [

        migrations.RemoveField(
            model_name='itemvariation',
            name='name',
        ),
        migrations.RemoveField(
            model_name='itemvariation',
            name='price',
        ),
        migrations.RemoveField(
            model_name='itemvariation',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='itemvariation',
            name='value',
        ),
    ]
