# Generated by Django 5.1.2 on 2024-10-27 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0003_alter_item_category_alter_itemvariantvalue_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='shipping',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
