# Generated by Django 5.1.2 on 2024-10-25 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Common', '0001_initial'),
        ('Inventory', '0004_remove_item_bullet_points_remove_item_delivery_time_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itemvariation',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='item',
            name='bullet_points',
        ),
        migrations.RemoveField(
            model_name='item',
            name='delivery_time',
        ),
        migrations.AddField(
            model_name='item',
            name='cross_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='discount_type',
            field=models.CharField(blank=True, choices=[('fixed', 'Fixed'), ('percentage', 'Percentage')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='item',
            name='tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='itemvariation',
            name='extra_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='itemvariation',
            name='images',
            field=models.ManyToManyField(related_name='variation_images', to='Common.image'),
        ),
        migrations.AddField(
            model_name='itemvariation',
            name='info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='return_policy',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='itemvariation',
            unique_together={('item', 'info')},
        ),
    ]
