# Generated by Django 5.1.2 on 2024-11-23 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0006_alter_category_parent_alter_item_brand_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineItem',
            fields=[
                ('id', models.CharField(editable=False, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.item')),
                ('variants', models.ManyToManyField(to='Inventory.itemvariantvalue')),
            ],
            options={
                'verbose_name': 'Pipeline Item',
                'verbose_name_plural': 'Pipeline Items',
                'db_table': 'pipeline_item',
            },
        ),
        migrations.CreateModel(
            name='CheckoutPipeline',
            fields=[
                ('id', models.CharField(editable=False, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('promotions', models.JSONField(blank=True, null=True)),
                ('order_note', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('items', models.ManyToManyField(to='Inventory.pipelineitem')),
            ],
            options={
                'verbose_name': 'Checkout Pipeline',
                'verbose_name_plural': 'Checkout Pipelines',
                'db_table': 'checkout_pipeline',
            },
        ),
    ]
