# Generated by Django 5.1.2 on 2024-11-27 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0008_promocode_order_state_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
