# Generated by Django 5.1.2 on 2024-11-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0007_pipelineitem_checkoutpipeline'),
        ('User', '0002_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='_items',
        ),
        migrations.AddField(
            model_name='address',
            name='is_billing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='address',
            name='type',
            field=models.CharField(choices=[('home', 'Home'), ('office', 'Office'), ('other', 'Other')], default='home', max_length=20),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='variants',
            field=models.ManyToManyField(related_name='cart_items', to='Inventory.itemvariantvalue'),
        ),
    ]
